"""Refresh `saizeriya/shops.py` from Saizeriya's public store search.

Scrapes paginated freeword search results and writes the resulting
`{store_name: shop_code}` mapping. Designed to be run on a schedule from CI.
"""

from __future__ import annotations

import argparse
import json
import logging
import re
from pathlib import Path

import httpx
from bs4 import BeautifulSoup, Tag

logger = logging.getLogger(__name__)

SEARCH_URL = "https://shop.saizeriya.co.jp/sz_restaurant/freeword"
SEARCH_PARAMS = {
    "word": "サイゼリヤ",
    "search-target": "name.address_name.search_word",
    "limit": "500",
}
USER_AGENT = "saizeriya-shop-updater (+https://github.com/eggplants/saizeriya)"
OUTPUT_PATH = Path(__file__).resolve().parent.parent / "saizeriya" / "shops.py"

CODE_PATTERN = re.compile(r"code=(\d+)")


def parse_page(html: str) -> list[tuple[str, str]]:
    """Extract `(name, code)` pairs from one page of search results."""
    soup = BeautifulSoup(html, "lxml")
    pairs: list[tuple[str, str]] = []
    for anchor in soup.select('a[href*="spot/detail?code="]'):
        if not isinstance(anchor, Tag):
            continue
        href = anchor.get("href")
        if isinstance(href, list):
            href = href[0] if href else None
        if not href:
            continue
        match = CODE_PATTERN.search(href)
        if not match:
            continue
        code = match.group(1)
        name = anchor.get_text(strip=True)
        if not name:
            continue
        pairs.append((name.replace("\u3000", " "), code))
    return pairs


def fetch_all(http: httpx.Client, *, limit: int = 500) -> list[tuple[str, str]]:
    """Walk pages until a partial page (< limit results) is returned."""
    collected: list[tuple[str, str]] = []
    page = 1
    while True:
        params = {**SEARCH_PARAMS, "limit": str(limit), "page": str(page)}
        response = http.get(SEARCH_URL, params=params)
        response.raise_for_status()
        page_pairs = parse_page(response.text)
        collected.extend(page_pairs)
        logger.info("page %d: %d entries", page, len(page_pairs))
        if len(page_pairs) < limit:
            break
        page += 1
    return collected


def deduplicate(pairs: list[tuple[str, str]]) -> dict[str, str]:
    """Collapse duplicates while warning if the same name maps to multiple codes."""
    seen: dict[str, str] = {}
    for name, code in pairs:
        if name in seen and seen[name] != code:
            logger.warning(
                "duplicate name %r -> %r, %r; keeping first",
                name,
                seen[name],
                code,
            )
            continue
        seen.setdefault(name, code)
    return seen


def render_module(shops: dict[str, str]) -> str:
    """Render the SHOPS mapping as a deterministic Python source file."""
    lines = [
        '"""Saizeriya store directory: store name → 4-digit shop code.',
        "",
        "Auto-generated by `scripts/update_shops.py` — do not edit by hand.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "SHOPS: dict[str, str] = {",
    ]
    # Sort by code for stable diffs.
    for name, code in sorted(shops.items(), key=lambda kv: (kv[1], kv[0])):
        key = json.dumps(name, ensure_ascii=False)
        value = json.dumps(code, ensure_ascii=False)
        lines.append(f"    {key}: {value},")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    """CLI entry point."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        type=Path,
        default=OUTPUT_PATH,
        help=f"output path (default: {OUTPUT_PATH})",
    )
    parser.add_argument("--limit", type=int, default=500, help="page size (default: 500)")
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the file would change",
    )
    args = parser.parse_args(argv)

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )

    headers = {"user-agent": USER_AGENT, "accept-language": "ja"}
    with httpx.Client(headers=headers, timeout=30.0, follow_redirects=True) as http:
        pairs = fetch_all(http, limit=args.limit)

    if not pairs:
        logger.error("no shops found")
        return 1

    shops = deduplicate(pairs)
    rendered = render_module(shops)

    out_path: Path = args.out
    previous = out_path.read_text(encoding="utf-8") if out_path.exists() else None
    if previous == rendered:
        logger.info("%s: unchanged (%d shops)", out_path, len(shops))
        return 0

    if args.check:
        logger.error("%s: would change", out_path)
        return 1

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(rendered, encoding="utf-8")
    logger.info("%s: wrote %d shops", out_path, len(shops))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
